const countries = [
  { name: "ASEAN", iso: "x-ASN" },
  { name: "Africa", iso: "x-AFR" },
  { name: "Argentina", iso: "ARG" },
  { name: "Asia", iso: "x-ASI" },
  { name: "Australia", iso: "AUS" },
  { name: "Austria", iso: "AUT" },
  { name: "Bangladesh", iso: "BGD" },
  { name: "Belgium", iso: "BEL" },
  { name: "Bolivia", iso: "BOL" },
  { name: "Bosnia Herzegovina", iso: "BIH" },
  { name: "Brazil", iso: "BRA" },
  { name: "Bulgaria", iso: "BGR" },
  { name: "Canada", iso: "CAN" },
  { name: "Chile", iso: "CHL" },
  { name: "China", iso: "CHN" },
  { name: "Colombia", iso: "COL" },
  { name: "Costa Rica", iso: "CRI" },
  { name: "Croatia", iso: "HRV" },
  { name: "Cyprus", iso: "CYP" },
  { name: "Czechia", iso: "CZE" },
  { name: "Denmark", iso: "DNK" },
  { name: "EU", iso: "x-EEU" },
  { name: "Ecuador", iso: "ECU" },
  { name: "Egypt", iso: "EGY" },
  { name: "El Salvador", iso: "SLV" },
  { name: "Estonia", iso: "EST" },
  { name: "Europe", iso: "x-EUR" },
  { name: "Finland", iso: "FIN" },
  { name: "France", iso: "FRA" },
  { name: "G20", iso: "x-G20" },
  { name: "G7", iso: "x-G07" },
  { name: "Georgia", iso: "GEO" },
  { name: "Germany", iso: "DEU" },
  { name: "Greece", iso: "GRC" },
  { name: "Hungary", iso: "HUN" },
  { name: "India", iso: "IND" },
  { name: "Iran", iso: "IRN" },
  { name: "Ireland", iso: "IRL" },
  { name: "Italy", iso: "ITA" },
  { name: "Japan", iso: "JPN" },
  { name: "Kazakhstan", iso: "KAZ" },
  { name: "Kenya", iso: "KEN" },
  { name: "Kosovo", iso: "XKX" },
  { name: "Kuwait", iso: "KWT" },
  { name: "Latin America and Caribbean", iso: "x-LAC" },
  { name: "Latvia", iso: "LVA" },
  { name: "Lithuania", iso: "LTU" },
  { name: "Luxembourg", iso: "LUX" },
  { name: "Malta", iso: "MLT" },
  { name: "Mexico", iso: "MEX" },
  { name: "Middle East", iso: "x-MDE" },
  { name: "Moldova", iso: "MDA" },
  { name: "Mongolia", iso: "MNG" },
  { name: "Montenegro", iso:"NE" },
  { name: "Morocco", iso: "MAR" },
  { name: "Myanmar", iso: "MMR" },
  { name: "Netherlands", iso: "NLD" },
  { name: "New Zealand", iso: "NZL" },
  { name: "Nigeria", iso: "NGA" },
  { name: "North America", iso: "x-NAM" },
  { name: "North Macedonia", iso: "MKD" },
  { name: "Norway", iso: "NOR" },
  { name: "OECD", iso: "x-OEC" },
  { name: "Oceania", iso: "x-OCN" },
  { name: "Oman", iso: "OMN" },
  { name: "Pakistan", iso: "PAK" },
  { name: "Peru", iso: "PER" },
  { name: "Poland", iso: "POL" },
  { name: "Portugal", iso: "PRT" },
  { name: "Puerto Rico", iso: "PRI" },
  { name: "Qatar", iso: "QAT" },
  { name: "Romania", iso: "ROU" },
  { name: "Russia", iso: "RUS" },
  { name: "Serbia", iso: "SRB" },
  { name: "Singapore", iso: "SGP" },
  { name: "Slovakia", iso: "SVK" },
  { name: "Slovenia", iso: "SVN" },
  { name: "South Africa", iso: "ZAF" },
  { name: "South Korea", iso: "KOR" },
  { name: "Spain", iso: "ESP" },
  { name: "Sweden", iso: "SWE" },
  { name: "Switzerland", iso: "CHE" },
  { name: "Taiwan", iso: "TWN" },
  { name: "Thailand", iso: "THA" },
  { name: "The Philippines", iso: "PHL" },
  { name: "Tunisia", iso: "TUN" },
  { name: "Türkiye", iso: "TUR" },
  { name: "Ukraine", iso: "UKR" },
  { name: "United Kingdom", iso: "GBR" },
  { name: "United States", iso: "USA" },
  { name: "Uruguay", iso: "URY" },
  { name: "Viet Nam", iso: "VNM" },
  { name: "World", iso: "x-WRD" },
];

module.exports = countries;